### ISSUE TITLE
Flowfile Attributes

### ISSUE THREAD

**Issue by CarrieRider** [apjansing/Nifi-Processors#3]
The processor isn't maintaining flow file attributes from those which are coming into it.

**Comment by apjansing** [comment]
Issue resolved in JsonFlattener processor and partially resolved in JsonAccordion -- still need to get JsonArrays to flatten properly and Jsons to compress.

https://github.com/apjansing/Nifi-Processors/commit/1bb37f00e378dd633e0d9c3fa9c13dadb68b7ebf

**Comment by apjansing** [comment]
Closing now that JsonAccordion is completed.
